### ISSUE TITLE
Error building `lineageos-16.0`

### ISSUE THREAD

**Issue by Peque** [MOTO-M8916/android_manifest#4]
When trying to `brunch osprey`, I get this error:

```
# brunch osprey
including vendor/lineage/vendorsetup.sh
Trying dependencies-only mode on a non-existing device tree?

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20190207-UNOFFICIAL-osprey
TARGET_PRODUCT=lineage_osprey
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.20.6-200.fc29.x86_64-x86_64-Ubuntu-16.04.5-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ2A.190205.001
OUT_DIR=/home/build/android/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8916 hardware/qcom/display-caf/msm8916 hardware/qcom/media-caf/msm8916
============================================
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20190207-UNOFFICIAL-osprey
TARGET_PRODUCT=lineage_osprey
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.20.6-200.fc29.x86_64-x86_64-Ubuntu-16.04.5-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ2A.190205.001
OUT_DIR=/home/build/android/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8916 hardware/qcom/display-caf/msm8916 hardware/qcom/media-caf/msm8916
============================================
ninja: no work to do.
ninja: no work to do.
No need to regenerate ninja file
No need to regenerate ninja file
[  0% 25/54929] build /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy
FAILED: /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy 
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 /home/build/android/out/host/linux-x86/bin/checkpolicy -M -c                 30 -o /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf ) && (/home/build/android/out/host/linux-x86/bin/sepolicy-analyze /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp permissive > /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ]; then             echo \"==========\" 1>&2;               echo \"ERROR: permissive domains not allowed in user builds\" 1>&2;    echo \"List of invalid domains:\" 1>&2;          cat /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains 1>&2;              exit 1;                 fi ) && (mv /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy )"
device/motorola/msm8916-common/sepolicy/hal_livedisplay_default.te:3:ERROR 'unknown type hal_livedisplay_default' at token ';' on line 76511:
allow hal_livedisplay_default qdisplay_service:service_manager find;
# Do not use add_service() as hal_graphics_composer_default may be the provider as well
checkpolicy:  error(s) encountered while parsing configuration
/home/build/android/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /home/build/android/out/target/product/osprey/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf
[  0% 34/54929] Building Kernel Config
make: Entering directory '/home/build/android/kernel/motorola/msm8916'
  GEN     /home/build/android/out/target/product/osprey/obj/KERNEL_OBJ/Makefile
#
# configuration written to .config
#
make: Leaving directory '/home/build/android/kernel/motorola/msm8916'
make: Entering directory '/home/build/android/kernel/motorola/msm8916'
  GEN     /home/build/android/out/target/product/osprey/obj/KERNEL_OBJ/Makefile
scripts/kconfig/conf --savedefconfig=defconfig Kconfig
make: Leaving directory '/home/build/android/kernel/motorola/msm8916'
ninja: build stopped: subcommand failed.
22:20:59 ninja failed with: exit status 1

#### failed to build some targets (20 seconds) ####
```

Any idea on what could be missing/wrong?

**Comment by thopiekar** [comment]
Please retry. It should work again.

**Comment by Peque** [comment]
@thopiekar I still get the same error. :confused:

**Comment by thopiekar** [comment]
Which OS are you using? Are you sure that the kernel build fails? Is your local manifest up-to-date?
I'm using Ubuntu Cosmic for example and it works here.

PS: I'm using the conventional way to build images: `source ./build/envsetup.sh; breakfast lux; brunch lux`

**Comment by Peque** [comment]
@thopiekar Manifest is definitely up-to-date. I am using a Docker image with Ubuntu 16.04.

The same happens whether I use `brunch` or `breakfast + lunch`.

I am building for Osprey though, not Lux. That might be the difference.

**Comment by thopiekar** [comment]
Yes, that could be the difference. Since it crashes at the same place where I had problems, maybe go through the sepolicy files for osprey and look for the file mentioned above.
Could be that you will get no working livedisplay after removing this file because of missing permissions, but at least having an image is a starting point.
Pretty sure that officially supported devices will have a similar file and up-to-date so we can copy and modify them hopefully.

**Comment by thopiekar** [comment]
Oh, sorry, the file is in -common and I made a PR for it already. All you need to do is to set -common in your manifest to my GitHub account and the branch mentioned in the PR:
https://github.com/MOTO-M8916/device_motorola_msm8916-common/pull/1

**Comment by Peque** [comment]
@thopiekar that fixed the issue, thanks! :blush:

Will try to flash it and see if everything works well.

**Comment by Peque** [comment]
@thopiekar Not really related to this, but do you know where https://github.com/twrp-m8916/twrp_recovery_manifest is now? Or did you need to download the compiled binary from https://androidfilehost.com/?w=files&flid=281333?

**Comment by thopiekar** [comment]
No idea where the sources are, but you will find a specific version "sep vendor" of TWRP on XDA.
Guess you will find more info in the thread.

**Comment by Peque** [comment]
I flashed the ROM and everything seems to be working great. :tada: :blush:

**Comment by thopiekar** [comment]
Perfect! Is there any livedisplay functionality? Something that might be implemented by Google and not LineageOS?

**Comment by Peque** [comment]
@thopiekar There is LiveDisplay in Settings, yeah:

<img src="https://user-images.githubusercontent.com/526577/54789684-964a3700-4c33-11e9-86e5-af92768d85b1.jpg" width="300">

What would you look for to see if there is something implemented by Google and not LineageOS?

**Comment by thopiekar** [comment]
For this, I think we would need to look into the source tree of LOS 16.0.
It happens often that Google picks up (similar) features, which have been implemented into previous versions.
So since these policies were needed in the past and now they are not needed anymore, it seems to me that something has majorly changed.

How about the camera? I think your phone has a different one than my lux, but would be great to know whether yours works or not. 😃

**Comment by Peque** [comment]
@thopiekar Yeah, everything seems to be working just fine: GPS, LTE, WiFi, camera (video, photos, QR)... And the battery life seems to be good too. :blush:

**Comment by Peque** [comment]
It seems to work fine now. :blush:
